name: CI
on: [push, pull_request]

jobs:
    security_and_build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install deps (dev)
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff mypy pytest bandit

            - name: Lint (ruff)
              run: ruff check .

            - name: Type check (mypy)
              run: mypy .

            - name: Unit tests
              run: pytest -q

            - name: SAST (bandit)
              run: bandit -r . -q

            - name: Secret scan (gitleaks)
              uses: gitleaks/gitleaks-action@v2

            - name: Build container
              run: docker build -t user-api:ci .

            - name: Container scan (trivy)
              uses: aquasecurity/trivy-action@0.24.0
              with:
                  image-ref: user-api:ci
                  severity: CRITICAL,HIGH
                  exit-code: "1"

            - name: Generate SBOM (syft)
              uses: anchore/sbom-action@v0
              with:
                  image: user-api:ci
